/* Auto-generated by genmsg_cpp for file /home/viki/ros_workspace/AU_UAV_stack/AU_UAV_ROS/srv/StartCoordinator.srv */
#ifndef AU_UAV_ROS_SERVICE_STARTCOORDINATOR_H
#define AU_UAV_ROS_SERVICE_STARTCOORDINATOR_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace AU_UAV_ROS
{
template <class ContainerAllocator>
struct StartCoordinatorRequest_ {
  typedef StartCoordinatorRequest_<ContainerAllocator> Type;

  StartCoordinatorRequest_()
  : indicator()
  {
  }

  StartCoordinatorRequest_(const ContainerAllocator& _alloc)
  : indicator(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _indicator_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  indicator;


  typedef boost::shared_ptr< ::AU_UAV_ROS::StartCoordinatorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::AU_UAV_ROS::StartCoordinatorRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct StartCoordinatorRequest
typedef  ::AU_UAV_ROS::StartCoordinatorRequest_<std::allocator<void> > StartCoordinatorRequest;

typedef boost::shared_ptr< ::AU_UAV_ROS::StartCoordinatorRequest> StartCoordinatorRequestPtr;
typedef boost::shared_ptr< ::AU_UAV_ROS::StartCoordinatorRequest const> StartCoordinatorRequestConstPtr;


template <class ContainerAllocator>
struct StartCoordinatorResponse_ {
  typedef StartCoordinatorResponse_<ContainerAllocator> Type;

  StartCoordinatorResponse_()
  : error()
  {
  }

  StartCoordinatorResponse_(const ContainerAllocator& _alloc)
  : error(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _error_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  error;


  typedef boost::shared_ptr< ::AU_UAV_ROS::StartCoordinatorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::AU_UAV_ROS::StartCoordinatorResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct StartCoordinatorResponse
typedef  ::AU_UAV_ROS::StartCoordinatorResponse_<std::allocator<void> > StartCoordinatorResponse;

typedef boost::shared_ptr< ::AU_UAV_ROS::StartCoordinatorResponse> StartCoordinatorResponsePtr;
typedef boost::shared_ptr< ::AU_UAV_ROS::StartCoordinatorResponse const> StartCoordinatorResponseConstPtr;

struct StartCoordinator
{

typedef StartCoordinatorRequest Request;
typedef StartCoordinatorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct StartCoordinator
} // namespace AU_UAV_ROS

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::AU_UAV_ROS::StartCoordinatorRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::AU_UAV_ROS::StartCoordinatorRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::AU_UAV_ROS::StartCoordinatorRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "31fd107e8c1178343ba30a7979504028";
  }

  static const char* value(const  ::AU_UAV_ROS::StartCoordinatorRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x31fd107e8c117834ULL;
  static const uint64_t static_value2 = 0x3ba30a7979504028ULL;
};

template<class ContainerAllocator>
struct DataType< ::AU_UAV_ROS::StartCoordinatorRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "AU_UAV_ROS/StartCoordinatorRequest";
  }

  static const char* value(const  ::AU_UAV_ROS::StartCoordinatorRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::AU_UAV_ROS::StartCoordinatorRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string indicator\n\
\n\
";
  }

  static const char* value(const  ::AU_UAV_ROS::StartCoordinatorRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::AU_UAV_ROS::StartCoordinatorResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::AU_UAV_ROS::StartCoordinatorResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::AU_UAV_ROS::StartCoordinatorResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "eca8b96616c32aacf1be8bbf14c70eba";
  }

  static const char* value(const  ::AU_UAV_ROS::StartCoordinatorResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xeca8b96616c32aacULL;
  static const uint64_t static_value2 = 0xf1be8bbf14c70ebaULL;
};

template<class ContainerAllocator>
struct DataType< ::AU_UAV_ROS::StartCoordinatorResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "AU_UAV_ROS/StartCoordinatorResponse";
  }

  static const char* value(const  ::AU_UAV_ROS::StartCoordinatorResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::AU_UAV_ROS::StartCoordinatorResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string error\n\
\n\
\n\
";
  }

  static const char* value(const  ::AU_UAV_ROS::StartCoordinatorResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::AU_UAV_ROS::StartCoordinatorRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.indicator);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct StartCoordinatorRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::AU_UAV_ROS::StartCoordinatorResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.error);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct StartCoordinatorResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<AU_UAV_ROS::StartCoordinator> {
  static const char* value() 
  {
    return "deeb10c2d9f6cfc01c3e0da763fa0b2b";
  }

  static const char* value(const AU_UAV_ROS::StartCoordinator&) { return value(); } 
};

template<>
struct DataType<AU_UAV_ROS::StartCoordinator> {
  static const char* value() 
  {
    return "AU_UAV_ROS/StartCoordinator";
  }

  static const char* value(const AU_UAV_ROS::StartCoordinator&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<AU_UAV_ROS::StartCoordinatorRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "deeb10c2d9f6cfc01c3e0da763fa0b2b";
  }

  static const char* value(const AU_UAV_ROS::StartCoordinatorRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<AU_UAV_ROS::StartCoordinatorRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "AU_UAV_ROS/StartCoordinator";
  }

  static const char* value(const AU_UAV_ROS::StartCoordinatorRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<AU_UAV_ROS::StartCoordinatorResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "deeb10c2d9f6cfc01c3e0da763fa0b2b";
  }

  static const char* value(const AU_UAV_ROS::StartCoordinatorResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<AU_UAV_ROS::StartCoordinatorResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "AU_UAV_ROS/StartCoordinator";
  }

  static const char* value(const AU_UAV_ROS::StartCoordinatorResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // AU_UAV_ROS_SERVICE_STARTCOORDINATOR_H

